### PR TITLE
Characteristics-Good-Programmer

### PR DESCRIPTION
**Pull request by nelson7787**

### CODE REVIEW

**Comment by nelson7787** [comment]
@JenniferRoubaud @teitel @an1905 What do you guys think??

**Comment by nelson7787** [comment]
@an1905 Thanks for the feedback - super helpful! Just incorporated it - let me know what you think.
@JenniferRoubaud @teitel What are your thoughts?

**Comment by teitel** [comment]
:+1: 
I would also add that he should be:
1) Able to come up with reusable functions/objects that solve the overall problem
2) Able to design systems that span multiple technologies/platforms
3) Able to use more than one framework in a professional capacity

**Comment by JenniferRoubaud** [comment]
@nelson7787 everything is fine for me Nelson. I agree with everyone's comments. Good work guys
:+1:

**Comment by nelson7787** [comment]
@gastonga10 Thank you - added in your comments! Let me know if ready :ship:

**Comment by teitel** [comment]
:+1:

**Comment by nelson7787** [comment]
@teitel Thanks for the input - incorporated. Check it out and let me know if it's ready to :ship:

**Comment by nelson7787** [comment]
@JenniferRoubaud @teitel @an1905 @gastonga10 Let me know if it's :+1: to :ship:

**Comment by an1905** [comment]
@nelson7787 I would maybe markdown the file a bit and add an image in! Other than that, LGTM ready to :ship !

**Comment by an1905** [comment]
@nelson7787 Sorry I meant LGTM ready to :ship:!! Just the markdown and image!

**Comment by nelson7787** [comment]
@an1905 Thanks for the feedback - image and markdown are already there :smile:

**Comment by nelson7787** [comment]
@an1905 made the picture visible - thanks for the tip!

**Pull request merged**
