### PR TITLE
Updated-Questions-to-Ask-When-Hiring

### PR DESCRIPTION
**Pull request by an1905**
@nelson7787 @teitel @JenniferRoubaud Apologies - I pressed the merge request button in the old thread by mistake! @teitel @nelson7787 Thanks for the feedback - have incorporated it here! @JenniferRoubaud Looking forward to your comments!

### CODE REVIEW

**Comment by nelson7787** [comment]
@an1905 removed the feedback from teitel that was in my pull request to keep things clean - his comment was to ask about compensation.

@an1905 Thanks for adding the suggestions I recommended in the other pull request (i.e., specifics around user experience, vision for organization, cultural integration when scaling, previous experience, etc)

**Comment by nelson7787** [comment]
@an1905 ready to :ship: on my end! thanks!

**Comment by an1905** [comment]
@gastonga10 Thanks - really helpful article - have referenced it as a link!

**Comment by gastonga10** [comment]
LGTM ready to :ship:

**Pull request merged**
